    # .github/workflows/backend-ci.yml

    name: Backend CI Pipeline

    on:
      push:
        branches: [ "main" ]
      pull_request:
        branches: [ "main" ]

    jobs:
      build-and-test:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            python-version: ["3.10"] # Use your project's Python version

        steps:
          - name: Check out repository code
            uses: actions/checkout@v4

          # --- DEBUG STEP: Add this to see the file structure ---
          - name: List files in workspace
            run: |
              echo "Current directory: $(pwd)"
              echo "Listing files recursively:"
              ls -R
          # --- END DEBUG STEP ---

          - name: Set up Python ${{ matrix.python-version }}
            uses: actions/setup-python@v5
            with:
              python-version: ${{ matrix.python-version }}
              # Keep cache enabled, let's see if the file exists first
              cache: 'pip'
              # Optional: Explicitly point to the requirements file if it's not at the root
              # cache-dependency-path: path/to/your/requirements.txt

          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              # This command assumes requirements.txt is in the root directory
              # where the command is run (usually the workspace root after checkout)
              pip install -r requirements.txt
              pip install pytest pytest-cov ruff # Install test/lint tools

          - name: Lint and Format Check with Ruff
            run: |
              ruff check . --output-format=github
              ruff format . --check

          - name: Run tests with Pytest
            run: |
              pytest --cov=app --cov-report=term-missing --cov-fail-under=80
            # env: ... (secrets if needed)

    