# .github/workflows/backend-ci.yml

name: Backend CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"] # Use your project's Python version

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: List files in workspace # Keep this for debugging
        run: |
          echo "Current directory: $(pwd)"
          echo "Workspace content:"
          ls -la
          echo "--- Recursive listing: ---"
          ls -R
          echo "--- End file listing ---"

      - name: Set up Python ${{ matrix.python-version }}
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          # --- Explicitly tell the action where the requirements file is ---
          # Assumes requirements.txt is in the root directory after checkout
          cache-dependency-path: requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Check if file exists before installing
          if [ -f requirements.txt ]; then
             echo "Found requirements.txt, installing dependencies..."
             pip install -r requirements.txt
          else
             echo "ERROR: requirements.txt not found in $(pwd)!"
             exit 1 # Fail the job explicitly
          fi
          pip install pytest pytest-cov ruff # Install test/lint tools

      - name: Lint and Format Check with Ruff
        run: |
          ruff check . --output-format=github
          ruff format . --check

      - name: Run tests with Pytest
        run: |
          pytest --cov=app --cov-report=term-missing --cov-fail-under=80
        # env: ... (secrets if needed)

